[global]
progress_full_character = "="
progress_empty_character = "="
progress_prefix = "["
progress_suffix = "]"
time_format = "%Y-%m-%d %H:%M:%S"

# [banner]
# color = "blue"
# command = "hostname | figlet -f slant"
# if you don't want a dependency on figlet, you can generate your
# banner however you want, put it in a file, and then use something like:
# command = "cat banner.txt"

[weather]
# url = "https://wttr.in/Leander,TX" # full report
# url = "https://wttr.in/Leander,TX?0" # for the current only
# url = "https://wttr.in/Leander,TX?uFn1q&lang=de" # u -> US units
# url = "https://wttr.in/Leander,TX?Fn1q&lang=de"
url = "https://wttr.in/Bielefeld,DE?Fn1q&lang=de"
# proxy = "http://proxy:8080"

# [service_status]
# Accounts = "accounts-daemon"
# Cron = "cron"

# [docker_status]
# Local containers MUST start with a slash
# https://github.com/moby/moby/issues/6705
# "/nextcloud-nextcloud-1" = "Nextcloud"
# "/nextcloud-nextcloud-mariadb-1" = "Nextcloud Database"

# [uptime]
# prefix = "Up"

# [user_service_status]
# gpg-agent = "gpg-agent"

# [ssl_certificates]
# sort_method = "manual"
#
#    [ssl_certificates.certs]
#    CertName1 = "/path/to/cert1.pem"
#    CertName2 = "/path/to/cert2.pem"

# [filesystems]
# root = "/"

# [memory]
# swap_pos = "beside" # "beside" or "below" or "none"

# [fail_2_ban]
# jails = ["sshd", "anotherjail"]

# [last_login]
# gabesaenz = 5

# [last_run]
