# schemes = ""
# templates = ""

# [[extra_scheme]]
# name = "tarko"
# source = "https://github.com/Softsun2/base16-tarko-scheme"

# [[extra_template]]
# name = "tarko"
# source = "https://github.com/Softsun2/base16-tarko-scheme"

[[item]]
file = "~/dotfiles/.config/.doom.d/themes/doom-base16-theme.el"
template = "doom"
rewrite = true

[[item]]
file = "~/dotfiles/.config/nvim/colors/base16.lua"
template = "nvim"
rewrite = true
hook = '~/dotfiles/.config/nvim/reload-colorscheme.sh'

[[item]]
file = "~/dotfiles/.config/kitty/base16.conf"
template = "kitty"
subtemplate = "default-256"
rewrite = true
hook = 'kitty +kitten themes --reload-in=all --config-file-name /tmp/kitty-theme.conf base16'

[[item]]
file = "~/dotfiles/.config/alacritty/base16.toml"
template = "alacritty"
subtemplate = "default-256"
rewrite = true

[[item]]
file = "~/dotfiles/.config/zathura/base16-theme"
template = "zathura"
subtemplate = "recolor"
rewrite = true
