# schemes = ""
# templates = ""

# [[extra_scheme]]
# name = "tarko"
# source = "https://github.com/Softsun2/base16-tarko-scheme"

# [[extra_template]]
# name = "tarko"
# source = "https://github.com/Softsun2/base16-tarko-scheme"

[[item]]
file = "~/dotfiles/.config/.doom.d/themes/doom-base16-theme.el"
template = "doom"
rewrite = true
hook = 'emacsclient --eval "(base16-theme-reload)" --quiet -no-wait --suppress-output -a true'

[[item]]
file = "~/dotfiles/.config/kitty/base16.conf"
template = "kitty"
rewrite = true
hook = 'kitty +kitten themes --reload-in=all --config-file-name /tmp/kitty-theme.conf base16'
